import streamlit as st
import pandas as pd


@st.cache
def convert_df(df):
    # IMPORTANT: Cache the conversion to prevent computation on every rerun
   return df.to_csv().encode('utf-8')


st.title('Dataset with the episodes of Arrow labeled with the topic generated by LDA')
dataset = pd.read_csv('Data/scripts.csv',  sep=';')
dataset.drop(['Unnamed: 0','Episodios'], axis=1, inplace=True)
dataset.rename(columns={'nome_ep': 'ep_name', 'nota_imdb': 'imbd_rating', 'qtd_reviews': ' number_reviews', 'Topic': 'predominant_topic'}, inplace=True)
st.dataframe(dataset)
st.sidebar.image("./img/arrow.jpeg")
st.sidebar.write('by: Anna Luiza')

csv = convert_df(dataset)

st.write('Visualize the clusters generated by LDA and the most frequent words of each topic: ')
agree1 = st.checkbox('Topic 1')

if agree1:
    st.image('img/topic1.jpeg')

agree2 = st.checkbox('Topic 2')

if agree2:
    st.image('img/topic2.jpeg')

agree3 = st.checkbox('Topic 3')

if agree3:
    st.image('img/topic3.jpeg')

st.download_button(
    label="Download data as CSV",
    data=csv,
    file_name='scripts_dataset.csv',
    mime='text/csv',
 )


